//
//  TaskEditorInteractor.swift
//  todo
//
//  Created by ismail palali on 12.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol TaskEditorBusinessLogic: AnyObject {
  func setupInitials(request: TaskEditor.SetupInitials.Request)
  func completeEntry(request: TaskEditor.CompleteEntry.Request)
}

final class TaskEditorInteractor {
  private let dataStore: TaskEditorDataStoreProtocol
  private let presenter: TaskEditorPresentationLogic
  
  init(dataStore: TaskEditorDataStoreProtocol,
       presenter: TaskEditorPresentationLogic) {
    
    self.dataStore = dataStore
    self.presenter = presenter
  }
}

extension TaskEditorInteractor: TaskEditorBusinessLogic {
  func setupInitials(request: TaskEditor.SetupInitials.Request) {
    let response = TaskEditor.SetupInitials.Response(initialText: dataStore.initialText)
    presenter.presentInitials(response: response)
  }
  
  func completeEntry(request: TaskEditor.CompleteEntry.Request) {
    dataStore.taskEditorOperationDidEnd?(request.text)
    
    let response = TaskEditor.CompleteEntry.Response()
    presenter.presentEntryCompletion(response: response)
  }
}

