//
//  TaskEditorPresenter.swift
//  todo
//
//  Created by ismail palali on 12.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TaskEditorPresentationLogic
{
  func presentSomething(response: TaskEditor.Something.Response)
}

class TaskEditorPresenter: TaskEditorPresentationLogic
{
  weak var viewController: TaskEditorDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: TaskEditor.Something.Response)
  {
    let viewModel = TaskEditor.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
