//
//  TaskEditorModels.swift
//  todo
//
//  Created by ismail palali on 12.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol TaskEditorDataStoreProtocol: AnyObject {
  var initialText: String? { get set }
  var taskEditorOperationDidEnd: TextHandler? { get set }
}

final class TaskEditorDataStore: TaskEditorDataStoreProtocol {
  var initialText: String?
  var taskEditorOperationDidEnd: TextHandler?
}
