//
//  TaskEditorInteractor.swift
//  todo
//
//  Created by ismail palali on 12.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TaskEditorBusinessLogic
{
  func doSomething(request: TaskEditor.Something.Request)
}

protocol TaskEditorDataStore
{
  //var name: String { get set }
}

class TaskEditorInteractor: TaskEditorBusinessLogic, TaskEditorDataStore
{
  var presenter: TaskEditorPresentationLogic?
  var worker: TaskEditorWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: TaskEditor.Something.Request)
  {
    worker = TaskEditorWorker()
    worker?.doSomeWork()
    
    let response = TaskEditor.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
