//
//  TaskEditorPresenter.swift
//  todo
//
//  Created by ismail palali on 12.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TaskEditorPresentationLogic: AnyObject {
  func presentInitials(response: TaskEditor.SetupInitials.Response)
  func presentEntryCompletion(response: TaskEditor.CompleteEntry.Response)
}

final class TaskEditorPresenter {
  private weak var displayer: TaskEditorDisplayLogic?
  
  init(displayer: TaskEditorDisplayLogic) {
    self.displayer = displayer
  }
}

extension TaskEditorPresenter: TaskEditorPresentationLogic {
  func presentInitials(response: TaskEditor.SetupInitials.Response) {
    let viewModel = TaskEditor.SetupInitials.ViewModel(initialText: response.initialText)
    displayer?.displayInitials(viewModel: viewModel)
  }
  
  func presentEntryCompletion(response: TaskEditor.CompleteEntry.Response) {
    let viewModel = TaskEditor.CompleteEntry.ViewModel()
    displayer?.displayEntryCompletion(viewModel: viewModel)
  }
}
