//
//  TaskEditorRouter.swift
//  todo
//
//  Created by ismail palali on 12.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TaskEditorRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol TaskEditorDataPassing
{
  var dataStore: TaskEditorDataStore? { get }
}

class TaskEditorRouter: NSObject, TaskEditorRoutingLogic, TaskEditorDataPassing
{
  weak var viewController: TaskEditorViewController?
  var dataStore: TaskEditorDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: TaskEditorViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: TaskEditorDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
