//
//  TaskListInteractor.swift
//  todo
//
//  Created by ismail palali on 12.02.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TaskListBusinessLogic
{
  func doSomething(request: TaskList.Something.Request)
}

protocol TaskListDataStore
{
  //var name: String { get set }
}

class TaskListInteractor: TaskListBusinessLogic, TaskListDataStore
{
  var presenter: TaskListPresentationLogic?
  var worker: TaskListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: TaskList.Something.Request)
  {
    worker = TaskListWorker()
    worker?.doSomeWork()
    
    let response = TaskList.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
